---
title: "BST260 Project"
author: "Sun M. Kim"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(caret)
```

# Data Wrangling
## Moore reef data from AIMS 

```{r}
# function to clean and wrangle AIMS Moore Reef data to deal with column names and column placement
clean_MooreReef_data <- function(df) {
    df[,2:ncol(df)] <- df[,1:ncol(df)]
    df[,1] <- rownames(df)
    df <- df %>% select(date, colnames(df)[ncol(df)])
    return(df)
}
```

```{r}
moore_reef_water_temp_2.0m <- read.csv("data/temp/AIMS_MooreReef_WaterTemperature_22Oct1997to16Feb2020_2.0m.csv", skip=108, sep= ",", row.names = NULL)
moore_reef_water_temp_9.0m <- read.csv("data/temp/AIMS_MooreReef_WaterTemperature_22Oct1997to17Dec2017_9.0m.csv", skip=94, sep= ",", row.names = NULL)

moore_reef_depth_1.9m <- read.csv("data/depth/AIMS_MooreReef_Depth_29Nov2009to21Apr2011_1.9m.csv", skip=49, sep= ",", row.names = NULL)
moore_reef_depth_9.2m <- read.csv("data/depth/AIMS_MooreReef_Depth_29Nov2009to24Feb2011_9.2m.csv", skip=49, sep= ",", row.names = NULL)


# run through function defined above to clean and wrangle data
moore_reef_water_temp_2.0m <- clean_MooreReef_data(moore_reef_water_temp_2.0m)
moore_reef_water_temp_9.0m <- clean_MooreReef_data(moore_reef_water_temp_9.0m)

moore_reef_depth_1.9m <- clean_MooreReef_data(moore_reef_depth_1.9m)
moore_reef_depth_9.2m <- clean_MooreReef_data(moore_reef_depth_9.2m)
```

```{r}
# merge AIMS Moore reef data
aims_data <- Reduce(function(x,y) merge(x,y, by="date"), list(moore_reef_water_temp_2.0m,
                                                              moore_reef_water_temp_9.0m,
                                                              moore_reef_depth_1.9m,
                                                              moore_reef_depth_9.2m))

# convert water temp data from string to numeric type
aims_data$Water.Temperature..2.0m.MORFL1.Reef.Flat.Site.1_LEVEL2_value_AVG <- 
    as.numeric(aims_data$Water.Temperature..2.0m.MORFL1.Reef.Flat.Site.1_LEVEL2_value_AVG)

aims_data$Water.Temperature..9.0m.MORSL1.Reef.Slope.Site.1_LEVEL2_value_AVG <- 
    as.numeric(aims_data$Water.Temperature..9.0m.MORSL1.Reef.Slope.Site.1_LEVEL2_value_AVG)
```


## Coral cover data
```{r}
# convert date-decimal in coral cover to YYYY-MM-DD format
coral_cover <- read.csv("data/trendgbr-coral-cover-with-ci.csv")
coral_cover$Date <- format(date_decimal(coral_cover$Date), "%Y-%m-%d")

# rename "Date" to "date"
names(coral_cover)[names(coral_cover) == "Date"] <- "date"
```


## Fish census data
```{r}
fish_census <- read.csv("data/Fish census 1992-2015.csv", sep="\t", header=T)

fish_census <- fish_census %>% select(gbifID, class, family, genus, species, verbatimScientificName, decimalLatitude, decimalLongitude, dateIdentified)
fish_census$dateIdentified <- ymd_hms(fish_census$dateIdentified)
```

Group fish census by date, then count how many unique fish species were observed on a given date
```{r}
fish_species_counts <- fish_census %>%
    arrange(dateIdentified) %>%
    group_by(dateIdentified) %>%
    summarise(num_of_species=n_distinct(species))

# rename "dateIdentified" to "date"
names(fish_species_counts)[names(fish_species_counts) == "dateIdentified"] <- "date"

```

Merge AIMS, coral cover and fish census data by data
```{r}
final_data <- Reduce(function(x,y) merge(x,y, by="date"), list(aims_data, coral_cover))

final_data <- final_data %>% select(-Upper.confidence.interval, -Lower.confidence.interval, -Confidence.interval.span)

write.csv(final_data, "final_data.csv", row.names = FALSE)
```


